---
title: "tarea3"
author: "gael villegas"
format: html
lang: es
# Descripcion: CSV de pokemon que contiene en su gran mayoría numeros correspondientes a las distintas variables de cada fila.
# Cantidad de filas: 800. Cantidad de columnas: 13
# Datos recuperados en: https://www.kaggle.com/datasets/sercanyesiloz/pokemon-data
toc: true
---

```{r}
#| label: Cargar-paquetes
#| warning: false
#| message: false
#| echo: false
# Carga de plotly
library(plotly)

# Carga de DT
library(DT)

# cargar dplyr
library(dplyr)

#cargar scales
library(scales)

# cargar tidyverse
library(tidyverse)
```

```{r}
#| label: Carga-de-Datos-CSV
#| warning: false
#| message: false
#| code-fold: true
# Carga de los datos de pokemon
pokemon <- read_csv("pokemon.csv")
```
```{r}
#| label: Datatable
#| warning: false
#| message: false
#| code-fold: true
DT:: datatable(pokemon)
```
```{r}
#| label: Conversion-necesaria-de-valor-numérico-a-caracter
#| warning: false
#| message: false
#| code-fold: true
generacion <- as.character(pokemon$Generation)
```

```{r}
#| label: Gráfico-1-Dispersión
#| warning: false
#| message: false
#| code-fold: true
grafico1 <- 
pokemon |>
ggplot(aes(x = Attack, y = Defense,
           color = `generacion`,
            text = paste0(
      "Nombre: ", Name, "\n")
      )
      ) +
  geom_point(size = 1.3) +
    scale_x_continuous(labels = label_comma(), limits = c(0, 200)) +
  ggtitle("Relacion entre puntos de ataque y defensa de los pokemon") +
  xlab("Ataque") +
  ylab("Defensa") +
  labs(caption = "Fuentes: Pokemon Data",
  color = "Generacion") +
  scale_colour_brewer(palette = "Set2") +
  theme_minimal()

ggplotly(grafico1)
```

```{r}
#| label: Agrupación
#| warning: false
#| message: false
#| code-fold: true
tiposdepokemon <-
  pokemon |>
  group_by(`Type 1`)
```
```{r}
#| label: Gráfico-2-Pastel
#| warning: false
#| message: false
#| code-fold: true
plot_ly(
  data = tiposdepokemon,
  labels = ~`Type 1`,
  values = ~`Generation`,
  type = "pie",
  textinfo = "label+percent",
  hoverinfo = "label+value+percent"
) |>
  layout(title = "Distribución de pokemon por Tipo Primario") |>
  config(locale = "es")
```

```{r}
#| label: Uso-de-dplyr
#| warning: false
#| message: false
#| code-fold: true
agua <-
pokemon |>
  filter(`Type 1` == "Water") |>
  group_by(Generation, Total) |>
  count(Generation)
```

```{r}
#| label: Gráfico-3-Cajas
#| warning: false
#| message: false
#| code-fold: true
grafico3 <-
  agua |>
  ggplot(aes(x = reorder(Generation, Total, median),
                y = Total)) +
  geom_boxplot(color = "#123456", fill = "#8AE550") +
  ggtitle("Total de puntos base para pokemon tipo agua por generación") +
  xlab("Generación") +
  ylab("Total")

ggplotly(grafico3) |>
  config(locale = 'es')
```

